import { SupabaseClient } from '@supabase/supabase-js'

export type DataSource = 'manual' | 'ai_categorized' | 'ai_receipt' | 'plaid_import' | 'crypto_sync' | 'system'

interface AuditEntry {
  table_name: string
  record_id: string
  action: 'insert' | 'update' | 'delete'
  old_data?: Record<string, unknown> | null
  new_data?: Record<string, unknown> | null
  source: DataSource
  user_id: string
}

export async function logAudit(supabase: SupabaseClient, entry: AuditEntry) {
  const { error } = await supabase.from('audit_log').insert(entry)
  if (error) {
    console.error('Failed to write audit log:', error)
  }
}

/**
 * Wraps a Supabase insert with automatic audit logging and quarantine check.
 * The data is always written (soft quarantine), but flagged if from AI source.
 */
export async function auditedInsert<T extends Record<string, unknown>>(
  supabase: SupabaseClient,
  tableName: string,
  data: T,
  source: DataSource,
  userId: string
): Promise<{ data: T | null; error: Error | null; quarantined: boolean }> {
  // Perform the insert
  const { data: inserted, error } = await supabase
    .from(tableName)
    .insert(data)
    .select()
    .single()

  if (error) {
    return { data: null, error: new Error(error.message), quarantined: false }
  }

  const recordId = (inserted as Record<string, unknown>).id as string

  // Log the audit entry
  await logAudit(supabase, {
    table_name: tableName,
    record_id: recordId,
    action: 'insert',
    old_data: null,
    new_data: inserted as Record<string, unknown>,
    source,
    user_id: userId,
  })

  // If source is AI, create a quarantine entry
  let quarantined = false
  if (['ai_categorized', 'ai_receipt'].includes(source)) {
    await quarantineRecord(supabase, {
      table_name: tableName,
      record_id: recordId,
      reason: `Auto-generated by ${source === 'ai_categorized' ? 'AI categorization' : 'AI receipt parser'}. Review for accuracy.`,
      severity: source === 'ai_receipt' ? 'high' : 'medium',
      source,
      data_snapshot: inserted as Record<string, unknown>,
      user_id: userId,
    })
    quarantined = true
  }

  return { data: inserted as T, error: null, quarantined }
}

/**
 * Wraps a Supabase update with audit logging.
 */
export async function auditedUpdate<T extends Record<string, unknown>>(
  supabase: SupabaseClient,
  tableName: string,
  recordId: string,
  oldData: Record<string, unknown>,
  newData: Partial<T>,
  source: DataSource,
  userId: string
): Promise<{ data: T | null; error: Error | null }> {
  const { data: updated, error } = await supabase
    .from(tableName)
    .update(newData)
    .eq('id', recordId)
    .select()
    .single()

  if (error) {
    return { data: null, error: new Error(error.message) }
  }

  await logAudit(supabase, {
    table_name: tableName,
    record_id: recordId,
    action: 'update',
    old_data: oldData,
    new_data: updated as Record<string, unknown>,
    source,
    user_id: userId,
  })

  return { data: updated as T, error: null }
}

async function quarantineRecord(
  supabase: SupabaseClient,
  entry: {
    table_name: string
    record_id: string
    reason: string
    severity: 'low' | 'medium' | 'high' | 'critical'
    source: string
    data_snapshot: Record<string, unknown>
    user_id: string
    suggested_fix?: Record<string, unknown>
  }
) {
  const { error } = await supabase.from('data_quarantine').insert({
    ...entry,
    status: 'pending',
  })
  if (error) {
    console.error('Failed to quarantine record:', error)
  }
}
